name: Build Vivify Quest

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
      - bugfix/**
      - feature/**
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl wget unzip git

      - name: Install QPM
      run: |
        mkdir -p /opt/qpm
        cd /opt/qpm
        wget https://github.com/QuestPackageManager/QPM.CLI/releases/download/v1.5.10/qpm-linux
        chmod +x qpm-linux
        sudo mv qpm-linux /usr/local/bin/qpm
        which qpm
        qpm --version
